[CH-107] Support Native RowToColumnar
Kyligence/ClickHouse pull request #114
Opened 2022-09-07 09:38 UTC by binmahone

Changelog category (leave one):
- New Feature
- Improvement
- Bug Fix (user-visible misbehaviour in official stable or prestable release)
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-09-07 10:56 UTC, liuneng1994 requested changes

2022-09-07 10:56 UTC, liuneng1994 commented on utils/local-engine/Parser/SparkRowToCHColumn.cpp
> +            throw std::runtime_error("doesn't support type " + String(magic_enum::enum_name(columns[i]->getDataType())));
优先使用clickhouse的Exception

2022-09-07 10:56 UTC, liuneng1994 commented on utils/local-engine/Parser/SparkRowToCHColumn.h
> +    SparkRowToCHColumnHelper(vector<string> names, vector<string> types, vector<bool> isNullables)
这里是不是可以传引用减少对象拷贝

2022-09-07 10:56 UTC, liuneng1994 commented on utils/local-engine/Parser/SparkRowToCHColumn.h
> +    DataTypePtr parseType(const string type, const bool isNullable)
type可以是引用

2022-09-07 10:56 UTC, liuneng1994 commented on utils/local-engine/local_engine_jni.cpp
> +    local_engine::SparkRowToCHColumn::spark_row_interator_class
没看到回收global class的代码

2022-09-08 06:57 UTC, zzcclp approved these changes
LGTM

2022-09-08 07:09 UTC, merged