Support datetime64
Kyligence/ClickHouse pull request #119
Opened 2022-09-14 14:58 UTC by taiyang-li

### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support datetime64

2022-09-14 14:58 UTC, kyligence-git commented
Can one of the admins verify this patch?

2022-09-15 01:57 UTC, liuneng1994 commented
test this please

2022-09-15 02:21 UTC, taiyang-li commented
I'm still working, no need for review for now, thanks!

2022-09-21 06:48 UTC, taiyang-li commented
> I'm still working, no need for review for now, thanks!

It is done.

2022-09-21 07:19 UTC, taiyang-li commented
Does anyone have time to review this PR, thanks!

2022-09-21 10:21 UTC, liuneng1994 commented
test this please

2022-09-22 03:04 UTC, liuneng1994 commented
test this please

2022-09-22 04:38 UTC, liuneng1994 requested changes

2022-09-22 04:38 UTC, liuneng1994 commented on utils/local-engine/Common/Logger.cpp
> +    Poco::Logger::root().setLevel("trace");
不要修改日志级别

2022-09-22 07:27 UTC, taiyang-li commented on utils/local-engine/Common/Logger.cpp
> +    Poco::Logger::root().setLevel("trace");
fixed

2022-09-22 08:36 UTC, liuneng1994 approved these changes
LGTM

2022-09-22 08:36 UTC, merged