[CH-190] enable tests in GlutenDataFrameAggregateSuite
Kyligence/ClickHouse pull request #192
Opened 2022-11-11 08:24 UTC by binmahone

Changelog category (leave one):
- New Feature
- Improvement
- Bug Fix (user-visible misbehaviour in official stable or prestable release)
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Not for changelog (changelog entry is not required)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2022-11-11 08:24 UTC, kyligence-git commented
Can one of the admins verify this patch?

2022-11-11 08:24 UTC, binmahone commented
test this please with 545

2022-11-11 08:43 UTC, binmahone commented
test this please with 545

2022-11-11 09:45 UTC, liuneng1994 commented on utils/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.cpp
> +namespace
这个放到local_engine的namespace下面吧

2022-11-11 09:46 UTC, liuneng1994 commented on utils/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.h
> +class AggregateFunctionPartialMerge final : public IAggregateFunctionHelper<AggregateFunctionPartialMerge>
同上，namespace

2022-11-11 09:51 UTC, liuneng1994 commented on utils/local-engine/local_engine_jni.cpp
> +    return x;
这里的作用是啥

2022-11-11 09:53 UTC, liuneng1994 requested changes
reviewed

2022-11-13 09:28 UTC, binmahone commented on utils/local-engine/local_engine_jni.cpp
> +    return x;
当时debug的时候改的 还原的时候没有100%还原 我来改一下

2022-11-13 10:41 UTC, binmahone commented
test this please with 545

2022-11-13 11:38 UTC, liuneng1994 approved these changes
LGTM

2022-11-13 11:38 UTC, merged