[CH-262] Skip memory copy between onheap and native when using columnar shuffle manager
Kyligence/ClickHouse pull request #263
Opened 2023-01-11 15:27 UTC by zzcclp

Changelog category (leave one):

Skip memory copy between onheap and native when using columnar shuffle manager.

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

2023-01-11 15:27 UTC, kyligence-git commented
Can one of the admins verify this patch?

2023-01-11 15:28 UTC, zzcclp commented
test this please with 840

2023-01-11 16:26 UTC, zzcclp commented
test this please with 840

2023-01-12 05:50 UTC, liuneng1994 commented on utils/local-engine/Builder/BroadCastJoinBuilder.cpp
> +    jint io_buffer_size;
jint 尽量别用换成size_t

2023-01-12 05:56 UTC, liuneng1994 commented on utils/local-engine/Shuffle/ShuffleSplitter.h
> +    size_t io_buffer_size = DEFAULT_BLOCK_SIZE;
这两个含义搞错了，split_size默认用default block size， io buffer size是buffer的大小不是block size

2023-01-12 05:57 UTC, liuneng1994 requested changes
改一下

2023-01-12 06:40 UTC, liuneng1994 approved these changes
LGTM

2023-01-12 07:22 UTC, merged